#! /bin/sh

echo 6
cd sketches/$1
base=`ls base*`
echo $base

echo "Creating color thumbnail"
convert $base -resize 128x128 orig.png
echo "Converting to grayscale"
convert -alpha off $base -set colorspace Gray -separate -average -normalize 0.png
echo "Drawing outlines"
convert 0.png -negate -blur 12 -fuzz 15% -edge 3 -negate -white-threshold 60% e.png
echo "Drawing crosshatch"
convert 0.png -white-threshold 50% -sketch 0x20+120 s.png
echo "Combining images"
composite -compose darken e.png s.png 1.pgm
echo "Creating sketch thumbnail"
convert -resize 128x128 1.pgm sketch.png
#potrace -t 1 -p 1.pgm
#pstoedit -f gcode 1.ps sketch.gcode
