#! /bin/sh

cd sketches/$1

convert base$2 -resize 128x128 orig.png
convert -alpha off base$2 -set colorspace Gray -separate -average -normalize 0.png
convert 0.png -negate -blur 12 -fuzz 15% -edge 3 -negate -white-threshold 60% e.png
convert 0.png -white-threshold 50% -sketch 0x20+120 s.png
composite -compose darken e.png s.png 1.pgm
convert -resize 128x128 1.pgm sketch.png
#potrace -t 1 -p 1.pgm
#pstoedit -f gcode 1.ps sketch.gcode
